accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
app_name='accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('passworld_change/', PasswordChangeView.as_view(), name='password_change'),
    path('passworld_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

]

app/urls.py
from django.contrib import admin
from django.urls import path, re_path
from app import views

app_name = 'app'

urlpatterns = [
    path('post/<int:pk>/', views.BlogDetailView.as_view(), name='post_detail'),
    path('post/create/', views.BlogCreateView.as_view(),name='post_create'),
    path('post/<int:pk>/update/', views.BlogUpdateView.as_view(),name='post_update'),
    path('post/<int:pk>/delete/', views.BloqDeleteView.as_view(),name='post_delete'),
    re_path(r'^vote/(?P<pk>\d+)/(?P<reaction>True|False)/$', views.vote, name='vote'),
    path('', views.BlogListView.as_view(), name='home'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('polls/', include('polls.urls')),
    path('',include('app.urls',namespace='app')),#говорим, что мы работаем сразу в app
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.contrib import admin
from django.urls import path
from polls import views

app_name = 'polls'

urlpatterns = [
    path('<int:pk>/results/', views.ResultsView.as_view(),name='results'),
    path('<int:id>/', views.polldetail,name='detail'),
    # path('<int:id>/vote/', views.vote, name='vote'),
    path('', views.IndexView.as_view(),name='index'),
]

templates/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title> Blog &nbsp;{% block title %} {% endblock title %}</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
		  integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
	<!--	<link rel="stylesheet" href="/static/css/base.css"/>-->
	<link rel="stylesheet" href='{% static "/css/base.css" %}'>
	<style>{%block style%} {% endblock style %}</style>
</head>
<body>
<a href="{% url 'app:home' %}"><img src="{% static 'img/blog.jpg' %}" height="150"></a>
<hr>
{% include 'messages_list.html' %}
<div class="container">
	{% block content %}

	{% endblock content %}
</div>
	{% include 'pagination.html' %}
</body>
</html>

templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
	<h2>Редактирование профиля</h2>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Редактиорвать</button>  &nbsp; &nbsp;<a href="{% url 'accounts:password_change' %}">Хотите изменить пароль?</a>
	</form>
	<br>
	<a href="{% url 'app:home' %}">Назад</a>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% block title %}Registration{% endblock title %}
{% block content %}
	<h2>Регистрация пользователя</h2>
	<form method="post"> {% csrf_token %}
		<div>
			{{ form.as_p }}
			<button type="submit" class="btn btn-primary"> Зарегистрировать</button>
		</div>
	</form>
{% endblock content %}