app/urls.py
from django.contrib import admin
from django.urls import path, re_path
from app import views

app_name = 'app'

urlpatterns = [
    path('post/<int:pk>/', views.BlogDetailView.as_view(), name='post_detail'),
    path('post/create/', views.BlogCreateView.as_view(),name='post_create'),
    path('post/<int:pk>/update/', views.BlogUpdateView.as_view(),name='post_update'),
    path('post/<int:pk>/delete/', views.BloqDeleteView.as_view(),name='post_delete'),
    re_path(r'^vote/(?P<pk>\d+)/(?P<reaction>True|False)/$', views.vote, name='vote'),
    path('', views.BlogListView.as_view(), name='home'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('polls/', include('polls.urls')),
    path('',include('app.urls',namespace='app')),#говорим, что мы работаем сразу в app
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.contrib import admin
from django.urls import path
from polls import views

app_name = 'polls'

urlpatterns = [
    path('<int:pk>/results/', views.ResultsView.as_view(),name='results'),
    path('<int:id>/', views.polldetail,name='detail'),
    # path('<int:id>/vote/', views.vote, name='vote'),
    path('', views.IndexView.as_view(),name='index'),
]

polls/models.py
from django.db import models
from polls import settings
from django.utils.safestring import mark_safe
from django.urls import reverse


class Question(models.Model):
    title = models.CharField('Заголовок', max_length=120)
    timestamp = models.DateTimeField('Дата создания', auto_now=False, auto_now_add=True)
    is_active = models.BooleanField(verbose_name='Опубликован')

    def __str__(self):
        return self.title

    def is_popular(self):
        answers = Answer.objects.filter(question_id=self.id)
        votes_total = sum([answer.votes for answer in answers])
        if votes_total > settings.POLLS_POPULAR_VOTES_LIMIT:
            img_path = settings.IMG_TRUE_PATH
        else:
            img_path = settings.IMG_FALSE_PATH
        return mark_safe('<img alt="" src="{}" />'.format(img_path))

    is_popular.short_description = 'Популярный'

    def total_votes(self):
        answers = Answer.objects.filter(question_id=self.id)
        return sum([answer.votes for answer in answers])

    total_votes.short_description = 'Всего голосов'

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class Answer(models.Model):
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=200, verbose_name="Ответ")
    votes = models.IntegerField(verbose_name="Голосов", default=0)

    def __str__(self):
        return self.answer

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import ListView, DetailView
from .models import Question, Answer
from django.urls import reverse

class IndexView(ListView):
    template_name = 'polls_question.html'

    def get_queryset(self):
        return Question.objects.order_by('-timestamp')[:3]

#
# class PollDetailView(DetailView):
#     model = Question
#     template_name = 'polls_detail.html'

def polldetail(request, id=None):
    question = get_object_or_404(Question, id=id)
    if request.method=='POST':
        if request.POST.get('answer'):
            try:
                selected_answer = question.answer_set.get(pk=request.POST['answer'])
            except(Answer.DoesNotExist):
                return render(request, 'polls_detail.html', {
                    'question': question,
                    'error_message': "Указан недопустимый ответ",
                })
            selected_answer.votes += 1
            selected_answer.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        else:
            return render(request, 'polls_detail.html', {
                'question': question,
                'error_message': "Вы не выбрали ответ.",
            })
    return render(request, 'polls_detail.html', {
        'question': question,
    })


class ResultsView(DetailView):
    model = Question
    template_name = 'polls_results.html'

polls/templates/polls_detail.html
{% extends 'base.html' %}
{% block title %}detail_question{% endblock title %}
{% block content %}
	{% if question.is_active %}
		<h1>{{ question.title }}</h1>
		{% if error_message %}
			<p><strong>{{ error_message }}</strong></p>
		{% endif %}
		{#	<form action="{% url 'polls:vote' question.id%}"  method="post">#}
		<form action="" method="post">
			{% csrf_token %}
			{% for answer in question.answer_set.all %}
				<p><input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}"/>
					<label for="answer{{ forloop.counter }}">{{ answer.answer }}</label></p>
			{% endfor %}
			<input type="submit" value="Голосовать"/>
		</form>
	{% else %}
		<p>Извините, опрос снят с публикации.</p>
	{% endif %}
{% endblock content %}

polls/templates/polls_question.html
{% extends 'base.html' %}
{% block title %}question{% endblock title %}
{% block content %}
	<h1>Последние опросы</h1>
	{% if object_list %}
		<ul>
			{% for question in object_list%}
				{% if question.is_active %}
				<li><a href="{% url 'polls:detail' question.pk %}" >{{ question.title }}</a></li>
					{% else %}
					<li>{{ question.title }} &nbsp;(Опрос снят с публикации)</li>
				{% endif %}
			{% endfor %}
		</ul>
	{% else %}
		<p>Опросы не найдены.</p>
	{% endif %}
	<p><i><a href="{% url 'app:home' %}" type="button" class="btn btn-secondary btn-sm"> На главную страницу</a></i></p>
{% endblock content %}

polls/templates/polls_results.html
{% extends 'base.html' %}
{% block title %}question_results{% endblock title %}
{% block content %}
	<h1>{{ question.title }}</h1>
	<ul>
		{% for answer in question.answer_set.all|dictsortreversed:"votes" %}
			<li>{{ answer.answer }} - голосов: {{ answer.votes }}</li>
		{% endfor %}
		<hr>
		<p>Всего проголосовали:{{ question.total_votes }}</p>
	</ul>
	<a href="{% url 'polls:index' %}">Другие опросы</a>
{% endblock content %}