accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
app_name='accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('passworld_change/', PasswordChangeView.as_view(), name='password_change'),
    path('passworld_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

]

app/urls.py
from django.contrib import admin
from django.urls import path, re_path
from app import views

app_name = 'app'

urlpatterns = [
    path('post/<int:pk>/', views.BlogDetailView.as_view(), name='post_detail'),
    path('post/create/', views.BlogCreateView.as_view(),name='post_create'),
    path('post/<int:pk>/update/', views.BlogUpdateView.as_view(),name='post_update'),
    path('post/<int:pk>/delete/', views.BloqDeleteView.as_view(),name='post_delete'),
    re_path(r'^vote/(?P<pk>\d+)/(?P<reaction>True|False)/$', views.vote, name='vote'),
    path('', views.BlogListView.as_view(), name='home'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('polls/', include('polls.urls')),
    path('',include('app.urls',namespace='app')),#говорим, что мы работаем сразу в app
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.contrib import admin
from django.urls import path
from polls import views

app_name = 'polls'

urlpatterns = [
    path('<int:pk>/results/', views.ResultsView.as_view(),name='results'),
    path('<int:id>/', views.polldetail,name='detail'),
    # path('<int:id>/vote/', views.vote, name='vote'),
    path('', views.IndexView.as_view(),name='index'),
]

app/templates/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title> Blog{% block title %} {% endblock title %}</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
		  integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
{#	<!--	<link rel="stylesheet" href="/static/css/base.css"/>-->#}
{#	<link rel="stylesheet" href='{% static "/css/base.css" %}'>#}

	<style>{%block style%} {% endblock style %}</style>
</head>
<body>
{% include 'messages_list.html' %}
<div class="container">
	{% block content %}

	{% endblock content %}
</div>
	{% include 'pagination.html' %}
</body>
</html>

app/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block style %}
	p.link_1 {
	text-align: right;
	}
{% endblock style %}
{% block content %}
	{% if user.is_authenticated %}
		<p>Hi {{ user.username }}!</p>
		<a href="{% url 'logout' %}">Выйти</a>
		<a href="{% url 'accounts:profile' user.pk %}">Редактировать профиль</a>
	{% else %}
		<p>Вы не авторизированны</p>
		<a href="{% url 'accounts:signup' %}">Регистрация</a>
		<a href="{% url 'login' %}">Войти</a>
	{% endif %}
	<p class="link_1"><a href="{% url 'polls:index' %}">Пройти опросы</a></p>
	<header>
		<h1><a href="{% url 'app:home' %}">Мой блог</a></h1>
	</header>
	<hr>
	{% if request.user.is_authenticated %}
		<a href="{% url 'app:post_create' %}" style="display: table; margin: 0 auto" class="btn btn-secondary btn-sm">Создать
			новый пост!</a>
	{% else %}
		<a href="{% url 'accounts:signup' %}" style="display: table; margin: 0 auto" class="btn btn-secondary btn-sm">Зарегистрируйтесь,
			чтобы написать пост!</a>
	{% endif %}
	<hr>
	{% for post in object_list %}
		<div class="post-entry">
			<h2><a href="{% url 'app:post_detail' post.pk %}">{{ post.title }}</a></h2>
			<p>{{ post.body }}</p>
			<small><p><i>{{ post.timestamp | timesince }}&nbsp; Автор:{{ post.author }}</i></p></small>
		</div>
	{% endfor %}

{% endblock content %}

app/templates/messages_list.html
<div class="message">
	{% if messages%}
	<ul class="messages">
		{%for message in messages%}
		<li {%if message.tags%} class="{{message.tags}}" {%endif%}>
			{%if "ok_h" in message.tags %}
			{{message|safe}}
			{%else%}
			{{message}}
			{%endif%}
		</li>
		{%endfor%}
	</ul>
	{% endif %}
</div>

app/templates/pagination.html
<div class="container">
	{% if page_obj.has_other_pages %}
		<nav id="pagination" class="col align-self-center" aria-label="Page navigation example">
			<ul class="pagination">
				{% if page_obj.number > 2 %}
					<li class="page-item"><a class="page-link" href="?page=1">1</a></li>
				{% endif %}
				{% if page_obj.has_previous %}
					<li class="page-item"><a class="page-link"
											 href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
					</li>
				{% else %}
					<li class="page-item disabled"><span class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</span>
					</li>
				{% endif %}
				{% for i in page_obj.paginator.page_range %}
					{% if i > page_obj.number|add:-2 and i < page_obj.number|add:2 %}
						{% if page_obj.number == i %}
							<li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ i }}</a>
							</li>
						{% else %}
							<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
						{% endif %}
					{% endif %}
				{% endfor %}
				{% if page_obj.has_next %}
					<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
					</li>
				{% else %}
					<li class="page-item disabled"><span class="page-link" href="#" tabindex="-1" aria-disabled="true">&raquo;</span>
					</li>
				{% endif %}
				{% if page_obj.number < page_obj.paginator.num_pages|add:-1 %}
					<li class="page-item"><a class="page-link"
											 href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
					</li>
				{% endif %}
			</ul>
		</nav>
	{% endif %}
</div>

app/templates/post_create.html
{% extends 'base.html' %}

{% block content %}
	<h1>{{ name }}</h1>
	<form method="POST" action="" enctype="multipart/form-data">
		{% csrf_token %}
		<p> Заголовок: {{ form.title }}</p>
		<p>Текст: {{ form.body }}</p>
		<p> Автор:{{ request.user}}</p>
		<p> Жанр:{{ form.status }}</p>
		<p>Загрузить картинку к посту:</p>
		<p>{{ form.image }}</p>
		<input type="submit" value='Создать пост'>
	</form>
{% endblock content %}

app/templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
	<h1>Delete post</h1>
	<form action="" method="post">
		{% csrf_token %}
		<p>Вы точно хотите удалить "{{ object.title }}"?</p>
		<input type="submit" value="Да" class="btn btn-secondary btn-sm" />
		<a href="{% url 'app:post_detail' object.id%}" type="button" class="btn btn-secondary btn-sm"> Нет</a>
	</form>
{% endblock content %}

app/templates/post_detail.html
{% extends 'base.html' %}
<style>{%block style%}
    h3 {
        color: deepskyblue;
    }
    .comment {
        border: 1px solid red;
        padding: 10px;
    }
{% endblock style %}</style>
{% block content %}
	<div>
		<h1>{{ get_post.title }}</h1>
			{%if get_post.image%}
			<p><img src="{{get_post.image.url}}" class="img-resposive"></p>
			{%endif%}
		<p>{{ get_post.body | linebreaks }}</p>
		<p><i>Создан: {{ get_post.timestamp }} Обновлен: {{ get_post.updated }}</i></p>
		<p>Автор:{{ get_post.author }}</p>
	{% ifequal get_post.author request.user%}
		<a href="{% url 'app:post_update' get_post.id%}" type="button" class="btn btn-secondary btn-sm"> Редактировать</a>
		<a href="{% url 'app:post_delete' get_post.id%}" type="button" class="btn btn-secondary btn-sm"> Удалить</a>

	{% endifequal %}
		<form method="POST" action="" enctype="multipart/form-data">
			{% csrf_token %}
			{% include 'vote_article.html' %}
		</form>
		{% if  get_post.comments.all %}
			<p>Комментарии:</p>
			{% for i in get_post.comments.all %}
				<div class="comment">
					<p>{{ forloop.counter }}</p>
					<p>{{ i.comment_text }}</p>
					<hr>
					<p>Создан: {{ i.timepublish }}&nbsp;Автор: {{ i.author }}</p>
				</div>
			{% endfor %}

			{% with get_post.comments.count as total_comments %}
				<p><i>Всего комметариев:{{ total_comments }}</i></p>
			{% endwith %}
		{% else %}
			<p>Пока нет комментариев</p>
		{% endif %}
		{% if request.user.is_authenticated %}
			<h3>Добавить комментарий</h3>
			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.as_p }}
				<input type="submit" value='Добавить комментарий'>
			</form>
		{% endif %}
	</div>
	<hr>
	<hr>
	<p><i><a href="{% url 'app:home' %}" type="button" class="btn btn-secondary btn-sm"> На главную страницу</a></i></p>
{% endblock content %}

app/templates/post_update.html
{% extends 'base.html' %}

{% block content %}
	<h1>{{ name }}</h1>
	<form method="POST" action="" enctype="multipart/form-data">
		{% csrf_token %}
		<p> Заголовок: {{ form.title }}</p>
		<p>Текст: {{ form.body }}</p>
		<p> Жанр:{{ form.status }}</p>
		<p>Загрузить картинку к посту:</p>
		<p>{{ form.image }}</p>
		<input type="submit" value='Peдактировать пост'>
	</form>
{% endblock content %}

app/templates/vote_article.html
<div class="votes">
	{% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
	{% endif %}
	<a href="{% url 'app:vote'  get_post.id 'True' %}">
		<i class="fas fa-thumbs-up">Лайк</i>
	</a>
	<span>
		{% if get_post.voteslike %}
			<i>{{ get_post.voteslike }}</i>
		{% else %}
			<i>0</i>
		{% endif %}
	</span>
	<a href="{% url 'app:vote'  get_post.id 'False' %}">
		<i class="fas fa-thumbs-down">Дизлайк</i>
	</a>
	<span>
		{% if get_post.votesdislike %}
			<i>{{ get_post.votesdislike }}</i>
		{% else %}
			<i>0</i>
		{% endif %}
	</span>
</div>